# package.yaml
name: mcp-server-starter
version: 1.2.0
description: TypeScript MCP server starter template with mcp-auth support and example tool
author: Patrick Michaelsen
license: MIT
homepage: https://github.com/prmichaelsen/acp-mcp-server-starter
repository: https://github.com/prmichaelsen/acp-mcp-server-starter.git

# Release configuration
release:
  branch: main

# Package contents
# Add files here as you create them
# Use @acp.pattern-create, @acp.command-create, @acp.design-create
# These commands automatically update this section
contents:
  patterns:
    - name: bootstrap
      file: mcp-server-starter.bootstrap.md
      description: Project initialization and directory structure
    
    - name: server-standalone
      file: mcp-server-starter.server-standalone.md
      description: Basic MCP server with stdio transport
    
    - name: server-factory
      file: mcp-server-starter.server-factory.md
      description: Multi-tenant server with mcp-auth integration
    
    - name: tool-creation
      file: mcp-server-starter.tool-creation.md
      description: MCP tool definition and implementation
    
    - name: build-config
      file: mcp-server-starter.build-config.md
      description: esbuild configuration for dual builds
    
    - name: test-config
      file: mcp-server-starter.test-config.md
      description: Jest configuration for TypeScript + ESM
    
    - name: config-management
      file: mcp-server-starter.config-management.md
      description: Environment variable and configuration management
  
  commands:
    - name: init
      file: mcp-server-starter.init.md
      description: Initialize new MCP server project with complete setup
    
    - name: add-tool
      file: mcp-server-starter.add-tool.md
      description: Generate new tool scaffolding with tests and registration
  
  designs:
    - name: architecture
      file: mcp-server-starter.architecture.md
      description: Overall MCP server architecture and dual export pattern
    
    - name: mcp-auth-integration
      file: mcp-server-starter.mcp-auth-integration.md
      description: Multi-tenant deployment with mcp-auth authentication

# Compatibility
requires:
  acp: >=2.8.0

# Tags for discovery
tags:
  - mcp
  - model-context-protocol
  - typescript
  - server
  - starter
  - template
  - mcp-auth
